<?php

/**
 * @file
 * Field placeholder module hooks and main functionality.
 *
 * This module gives support to add HTML5 placeholder
 * attribute to field widget forms.
 */

/**
 * Implements hook_field_form_field_ui_field_edit_form_alter().
 */
function field_placeholder_form_field_ui_field_edit_form_alter(&$form, &$form_state) {
  if (in_array($form['#instance']['widget']['type'], field_placeholder_get_widget_types())) {
    $settings = isset($form['#instance']) ? $form['#instance'] : array();

    $form['instance']['placeholder_wrapper']['placeholder'] = array(
      '#type' => 'textfield',
      '#title' => t('Placeholder'),
      '#description' => t('Placeholder value for this field instance.'),
      '#default_value' => isset($settings['placeholder']) ? $settings['placeholder'] : '',
      '#parents' => array('instance', 'placeholder'),
      '#maxlength' => 512,
      '#states' => array(
        'visible' => array(
          ':input[name="instance[use_title_as_placeholder]"]' => array('value' => 0),
        )
      )
    );
  }
}

/**
 * Returns information about field widgets from hook_field_placeholder_info().
 *
 * @return array
 *   An array containing all the Field placeholder available widgets
 *   information.
 */
function field_placeholder_get_widgets() {
  $widgets = &drupal_static(__FUNCTION__);

  if (!$widgets) {
    $widgets = module_invoke_all('field_placeholder_info');
    $widgets = (is_array($widgets)) ? $widgets : array();
  }

  return $widgets;
}

/**
 * Returns an array with names of all the placeholder available widgets.
 *
 * @return array
 *   Array containing all the Field placeholder available widgets name.
 */
function field_placeholder_get_widget_types() {
  $widgets = field_placeholder_get_widgets();
  return array_keys($widgets);
}

/**
 * Implements hook_field_placeholder_info().
 */
function field_placeholder_field_placeholder_info() {
  return array(
    'text_textfield' => 'value',
    'text_textarea' => 'value',
    'text_textarea_with_summary' => 'summary',
    'number' => 'value',
    'email_textfield' => 'email',
    'phone_textfield' => 'value',
  );
}
