<?php 

  function decanatura_blocks_block_info(){
    $blocks = array();
    $blocks['user_menu_block'] = array(
      'info' => t('User Menu'),
    );
    $blocks['deca_main_menu_block'] = array(
      'info' => t('Decanatura Main Menu'),
    );
    $blocks['deca_footer_other_sites_block'] = array(
      'info' => t('Footer Other Sites'),
    );
    $blocks['deca_footer_info_block'] = array(
      'info' => t('Footer Info'),
    );
    return $blocks;
   }

  function decanatura_blocks_block_configure($delta=''){
    $form = array();
    switch($delta) {
      case 'deca_main_menu_block': 
        $form['logo_andes'] = array(
          '#name' => 'logo_andes',
          '#type' => 'managed_file',
          '#description' => t('Select an image'),
          '#default_value' => variable_get('logo_andes',''),
          '#upload_location' => 'public://andes_images/',
          '#upload_validators' => array(
            'file_validate_extensions' => array('png JPG')
          ),
        );
        $form['logo_decanatura'] = array(
          '#name' => 'logo_decanatura',
          '#type' => 'managed_file',
          '#description' => t('Select an image'),
          '#default_value' => variable_get('logo_decanatura',''),
          '#upload_location' => 'public://andes_images/',
          '#upload_validators' => array(
            'file_validate_extensions' => array('png JPG')
          ),
        );
        $form['logo_buscador'] = array(
          '#name' => 'logo_buscador',
          '#type' => 'managed_file',
          '#description' => t('Select an image'),
          '#default_value' => variable_get('logo_buscador',''),
          '#upload_location' => 'public://andes_images/',
          '#upload_validators' => array(
            'file_validate_extensions' => array('png JPG')
          ),
        );
        break;
      case 'deca_footer_info_block':
        $form['logo_andes'] = array(
          '#name' => 'logo_andes',
          '#type' => 'managed_file',
          '#description' => t('Select an image'),
          '#default_value' => variable_get('logo_andes_2',''),
          '#upload_location' => 'public://andes_images/',
          '#upload_validators' => array(
            'file_validate_extensions' => array('png JPG')
          ),
        );

        $form['logo_decanatura'] = array(
          '#name' => 'logo_decanatura',
          '#type' => 'managed_file',
          '#description' => t('Select an image'),
          '#default_value' => variable_get('logo_decanatura_2',''),
          '#upload_location' => 'public://andes_images/',
          '#upload_validators' => array(
            'file_validate_extensions' => array('png JPG')
          ),
        );
        $form['contact_info'] = array(
          '#name' => 'contact_info',
          '#type' => 'text_format',
          '#description' => t('Contact Info'),
          '#default_value' => variable_get('contact_info',''),
        );

        break;
    }
    return $form;
  } 


  function decanatura_blocks_block_save($delta = '', $edit = array()) {
    switch($delta) {
      case 'deca_main_menu_block':
        $file = file_load($edit['logo_andes']);
        $file->status = FILE_STATUS_PERMANENT;
        file_save($file);
        $block = block_load('decanatura_blocks', $delta);
        file_usage_add($file, 'decanatura_blocks', 'block', $block->bid);
        variable_set('logo_andes', $file->fid);
        $file = file_load($edit['logo_decanatura']);
        $file->status = FILE_STATUS_PERMANENT;
        file_save($file);
        $block = block_load('decanatura_blocks', $delta);
        file_usage_add($file, 'decanatura_blocks', 'block', $block->bid);
        variable_set('logo_decanatura', $file->fid);
        $file = file_load($edit['logo_buscador']);
        $file->status = FILE_STATUS_PERMANENT;
        file_save($file);
        $block = block_load('decanatura_blocks', $delta);
        file_usage_add($file, 'decanatura_blocks', 'block', $block->bid);
        variable_set('logo_buscador', $file->fid);
        break;
      case 'deca_footer_info_block':
        $file = file_load($edit['logo_andes']);
        $file->status = FILE_STATUS_PERMANENT;
        file_save($file);
        $block = block_load('decanatura_blocks', $delta);
        file_usage_add($file, 'decanatura_blocks', 'block', $block->bid);
        variable_set('logo_andes_2', $file->fid);
        $file = file_load($edit['logo_decanatura']);
        $file->status = FILE_STATUS_PERMANENT;
        file_save($file);
        $block = block_load('decanatura_blocks', $delta);
        file_usage_add($file, 'decanatura_blocks', 'block', $block->bid);
        variable_set('logo_decanatura_2', $file->fid);
        variable_set('contact_info', $edit['contact_info']['value']);
        break;
    }
  }

  function decanatura_blocks_block_view($delta = '') {
    $block = array();
    switch ($delta) {
      case 'user_menu_block':
         $variables = array();
         $block['content']   = theme('user_menu_block', $variables);
         break;
      case 'deca_main_menu_block':
         $variables = array();
         $block['content']   = theme('deca_main_menu_block', $variables);
         break;
      case 'deca_footer_other_sites_block':
         $variables = array();
         $block['content']   = theme('deca_footer_other_sites_block', $variables);
         break;
      case 'deca_footer_info_block':
         $variables = array();
         $block['content']   = theme('deca_footer_info_block', $variables);
         break;
    }
    return $block;
  }

  function decanatura_blocks_theme() {
    return array(
      'user_menu_block' => array(
        'template' => 'user_menu_block',
        'variables' => array(),
        'path' => drupal_get_path('module','decanatura_blocks') ."/templates",
      ),
      'deca_main_menu_block' => array(
        'template' => 'deca_main_menu_block',
        'variables' => array(),
        'path' => drupal_get_path('module','decanatura_blocks') ."/templates",
      ),
      'deca_footer_other_sites_block' => array(
        'template' => 'deca_footer_other_sites_block',
        'variables' => array(),
        'path' => drupal_get_path('module','decanatura_blocks') ."/templates",
      ),
      'deca_footer_info_block' => array(
        'template' => 'deca_footer_info_block',
        'variables' => array(),
        'path' => drupal_get_path('module','decanatura_blocks') ."/templates",
      )
    );
  }